### ISSUE TITLE
Slide with babel results but not source?

### ISSUE THREAD

**Issue by acowley** [positron-solutions/dslide#1]
Thank you for sharing this package! Something I'm running into is that I often have parts of an org document that I'd like to hide from the presentation. I'm not sure how to entirely skip over certain headings during a presentation (I can set the action to `nil` and have a blank screen), but the trickier one is that I often have a `src` block that generates a figure, and I would like the slide contents to be a title and the figure image, without the code. Is this an available slide style that I just haven't noticed yet?

**Comment by psionic-k** [comment]
https://github.com/positron-solutions/dslide/blob/master/test/demo.org#hidden-babel-slide

The hidden babel slide is an example of hiding some babel blocks and using them to change the contents of the parent.

For a more blunt solution, let's assume you want the figure to appear immediately.  You don't need a child heading.  Instead, you can make the babel block hide itself:
```org
* Clandestine Babel
:PROPERTIES:
:DSLIDE_SECTION_ACTIONS: dslide-action-babel
:END:
Since the document is made out of Elisp, it can hide its own contents during the begin and end, so you will never see the babel block that does not exist below:
#+attr_dslide: begin end
#+begin_src elisp :results none
  ;; you can run this expression before or after the block you want to hide
  (let* ((block (org-element-at-point))
         (overlay (make-overlay (org-element-property :begin block)
                                (org-element-property :end block))))
    (overlay-put overlay 'display "")
    (push overlay dslide--overlays))
#+end_src
```
* The point is within the babel block at the time this block is run, so `org-element-at-point` will be the `src-block` element
* `dslide--overlays` is a dumping ground for various parts of `dslide` to create an overlay and let it get cleaned up after the current slide is no longer visible.  Maybe I should make this public in a future release so that anyone can rely on this behavior.

I think I will add a behavior to hide labelled elements.

I may also enable the babel block action to work as a child action.  In my imagination, it feels cleaner if the babel blocks are stored in a child heading that is never seen.  Do others feel this way?  :rocket:

**Comment by acowley** [comment]
Thank you for explaining! I did consider the hidden babel slide in the demo, but it was more complexity than I was hoping for. I was thinking of this as a kind of export scenario, where the block header `:exports` flag controls things quite nicely. I think the use-case of having code generate figures for slides is common enough to specifically consider.

**Comment by psionic-k** [comment]
This makes sense, though I don't use that `:exports` property.  I am giving the mailing list some time to provide feedback regarding whether it's consistent with use.

I do intend to support hiding directly.  I've found it to be too useful to remain hidden away in `master-of-ceremonies`.

I might actually deprecate that style of "hidden babel" as I found an annoyance about its implementation.

**Comment by psionic-k** [comment]
Check the behavior I experimentally implemented in https://github.com/positron-solutions/dslide/tree/babel-results-and-exports

The last two commits are regarding results handling and exports.

It's just a rough sketch implementation:
- When clearing results going backwards, I need to actually map over all blocks that were skipped and remove any old results unless those blocks append results
- The overlays are including part of the results because of how overlays grow or shrink. There's an option to tune them.  I might need to change how they map, but I didn't look at how org does post-affiliated or whatever for results or if it's a separate element or not.
- Results are taking up a lot of vertical space, and I'd like to not pad them with newlines during presentation
- Some combinations seem pretty confusing.  Some more feedback even during the presentation might be warranted.

**Comment by psionic-k** [comment]
`:exports none` and `:exports results` are now supported in master.  There are more examples and new capabilities in the demo.org.  Cheers!

If there's related asks, please re-open or file a new issue.
